package ipc

import (
	"crypto/rand"
	"encoding/json"
	"fmt"
)

// Message is the wire format for IPC communication between the proxy and the
// control plane. Messages are serialized as newline-delimited JSON.
//
// Fields:
//   - Type:  the message type, e.g. "request.logged", "approval.needed",
//     "rules.reload", "agents.reload", "config.update",
//     "approval.resolve".
//   - MsgID: a unique identifier for this message. Auto-generated by [Frame]
//     if empty.
//   - Ref:   optional reference to a previous MsgID, used to correlate
//     responses (e.g., approval.resolve references approval.needed).
//   - Data:  opaque JSON payload whose schema depends on the message Type.
type Message struct {
	Type  string          `json:"type"`
	MsgID string          `json:"msg_id"`
	Ref   string          `json:"ref,omitempty"`
	Data  json.RawMessage `json:"data,omitempty"`
}

// GenerateID returns a cryptographically random 128-bit hex string suitable
// for use as a MsgID.
func GenerateID() string {
	b := make([]byte, 16)
	rand.Read(b)
	return fmt.Sprintf("%x", b)
}

// Frame serializes a [Message] to a newline-terminated JSON byte slice ready
// for transmission over the IPC socket. If m.MsgID is empty, a random ID is
// assigned via [GenerateID].
func Frame(m Message) []byte {
	if m.MsgID == "" {
		m.MsgID = GenerateID()
	}
	b, _ := json.Marshal(m)
	return append(b, '\n')
}
